# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fbc74deb5c8e50b096f327981a6ad0863cedbf5929e31a1a79f5a14c4e518ae3ff9e1b28d4ee388e8f8be29446b4227cdb939dcefcafef0ffb0fba9b32ad506

test:
  secret_key_base: d5ac01fab82da683e81362daef876306029dd25981dab4ce38da3bf273326f36ce15a754469f1873787efb097fd01c985ca97cd13ee4d398fa64db339489d470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
